### ISSUE TITLE
[bug] No such file or directory: /Users/joe/.js/.jsrc

### ISSUE THREAD

**Issue by jsjoeio** [johnlindquist/simplescripts#1]
When I start iTerm for the first time, it prints this message before starting

<img width="952" alt="image" src="https://user-images.githubusercontent.com/3806031/101990168-858cf080-3c62-11eb-901c-4e6f0777a962.png">

**Comment by zacjones93** [comment]
I believe this is because the project got moved to a `.simple` directory which is what will be used from here on out.

You should be able to delete the config trying to source that `.js` file 

The updated config looks like this:
```
source /Users/zac/.simple/.simplerc
```

**Comment by johnlindquist** [comment]
@jsjoeio yeah, open your `~/.zshrc` and delete the `source ~/.js/.jsrc` line

**Comment by jsjoeio** [comment]
Ah, didn't even think of that! Thanks all!
