### ISSUE TITLE
atom not launching as editor. osx big sur

### ISSUE THREAD

**Issue by cfritze64** [johnlindquist/simplescripts#39]
launching scripts for editing from the app or the terminal interface doesn't open the file for editing in the Atom editor. 

Here's an example when I ask simple to edit the .env file. In my .env, SIMPLE_EDITOR=atom
calling atom from the terminal command line (outside simple) works.

![Screenshot of TerminalScreenshot of Terminal (2-14-21, 10-13-01 PM)](https://user-images.githubusercontent.com/13821327/107911688-e1e5e800-6f11-11eb-8a64-91a2a9c60da2.jpg)

**Comment by johnlindquist** [comment]
Run 'which atom' in your terminal and use the full path in the .env.

(Simple doesn't have all of the $PATH that your terminal does)

**Comment by cfritze64** [comment]
(working late!)
no joy
which atom returns  /usr/local/bin/atom
but setting that in .env doesn't change the behavior. Maybe it's atom's problem?

**Comment by johnlindquist** [comment]
I'll check tomorrow. Just saw the notification on my phone in bed, lol

**Comment by johnlindquist** [comment]
@cfritze64 Can you run `git pull` from your `.simple` dir and try again?

**Comment by cfritze64** [comment]
That worked a treat. Many thanks!
