### ISSUE TITLE
share-file example script fails when ran out of the box

### ISSUE THREAD

**Issue by edgebal** [johnlindquist/simplescripts#5]
When using it "out of the box", `share-file` example script fails, as it seems it requires `SIMPLE_TMP_DIR` environment variable being set.

Unless intentional, I think this can be defaulted (on the script) to use Node's `os.tmpdir()`.

PS: Loving Simple Scripts so far ❤️ !

### Environment
- OS: macOS Big Sur 11.1

### Logs

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at Proxy.join (node:path:1081:7)
    at file:///Users/------/.simple/src/share-file.js:33:24 {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by johnlindquist** [comment]
@edgebal Should be fixed now. Run `simple` and it should prompt you to update :)

**Comment by johnlindquist** [comment]
@edgebal Also, please let me know if you have any questions over in discussions. Happy to help you explore creating scripts

**Comment by edgebal** [comment]
Works like a charm now! Thanks!

Looking forward to use `simple` for my daily workflow. I love the way it manages dependencies and how easy is to share scripts.
